### PR TITLE
Report modifiers of classes and methods

### PR DESCRIPTION
**Pull request by jazzmuesli**
Sometimes it is useful to know whether it's an abstract class or a private method/etc.

### CODE REVIEW

**Comment by jazzmuesli** [comment]
> Hi, @jazzmuesli! Thanks for this very useful PR!
> 
> Before merging it, can I ask you to write a few words about this new _modifier_ attribute in the README? And, more specifically, how one can interpret this integer number (a reference to the `javaassist.Modifier` javadoc should work!)

Autocomplete was wrong to suggest javaassist.Modifer, java.lang.reflect.Modifier can be used - I've updated references and ModifiersTest.

**Comment by mauricioaniche** [comment]
Now that you said it, should we use `org.eclipse.jdt.core.dom.Modifier`? This is the JDK one, right?

**Comment by mauricioaniche** [comment]
After talking to you in person, I checked CK's codebase, and we are using Eclipse's `Modifier` in other classes. Although they do basically the same thing, just so that we have a standard way of doing it, would you mind changing the current code to use the Eclipse's one?

**Comment by jazzmuesli** [comment]
> After talking to you in person, I checked CK's codebase, and we are using Eclipse's `Modifier` in other classes. Although they do basically the same thing, just so that we have a standard way of doing it, would you mind changing the current code to use the Eclipse's one?

Done.

**Comment by jazzmuesli** [comment]
Hi @mauricioaniche, could you deploy the latest version to mvnrepository as 0.3.2 ? I'll try to build/ deploy my ck-mvn-plugin. Thanks!

**Pull request merged**
