### PR TITLE
Feature/integration git repository

### PR DESCRIPTION
**Pull request by leandroungari**
The current implementation analyses the current version of source code in a local folder. When we use a version control, we need to manage multiple version of source code. 

Then, the new feature integrates the metrics analysis to differents versions (commits - RevCommit) of a repository. To do that, we use the JGit library.

### CODE REVIEW

**Comment by mauricioaniche** [comment]
Hi, @leandroungari, thanks for the PR!

I think analysing source code of different versions of the system should not be the responsibility of this CK tool. There are so many different ways to visit a repo (e.g., skipping merge commits, or visiting every other 500 commits, or visit tags, etc etc). This feature will quickly become very complex.

Right now, I think you should write an external tool that visits your repo (maybe using the old RepoDriller, or the new Pydriller) and, to each version, you then run CK there. 

Does that make sense to you?

**Comment by leandroungari** [comment]
Hey, @mauricioaniche , whether we look towards in this perspective, it makes sense. In fact, there is a lot of ways to walk over a repository.

My initial intent to add this feature was to avoid the "hard work" of reading/writing operation on disk because the current implementation looks over the stored state in the file system, and there is no way to provide the source code directly (from a different version).

So, I think that a better feature would be the possibility of entering the source code in the CK tool.

**Comment by mauricioaniche** [comment]
Hi, @leandroungari. The advantage of feeding an entire folder is that you enable JDK to build relationships about the classes (i.e., `resolveBindings()`).

If you feel like you don't need those relationships and you only care about one class, maybe you can introduce a method `calculate(String clazz)` or something that runs the metric for the code inside of the string.

I strongly believe we should not introduce JGit here.

**Comment by leandroungari** [comment]
Yes, a new feature must be able to emulate the folder hierarchy. I guess it is solved, we may close this issue.

**Pull request closed without merging**
